# Generated by Django 5.2.15 on 2026-07-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("listing_inquiry", "Listing inquiry"),
                    ("listing_author_contact", "Listing author contact"),
                    ("location_reported", "Location reported"),
                    ("listing_expiring", "Listing expiring soon"),
                    ("listing_expired", "Listing expired"),
                    ("listing_resolved", "Listing resolved"),
                    ("nearby_listing", "Nearby listing"),
                ],
                help_text="What kind of event triggered this notification",
                max_length=50,
            ),
        ),
    ]
