# Generated by Django 5.2.14 on 2026-05-26 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('listings', '0002_alter_listing_search_radius_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='listings.listing'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'public')), fields=('listing',), name='unique_public_conversation_per_listing'),
        ),
    ]
