# Generated by Django 5.2.15 on 2026-07-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listing_search_radius_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="expiring_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the 'expiring soon' warning was sent (once)",
                null=True,
            ),
        ),
    ]
